
function getmimetype(filename) {
	var fn = new string(filename);
	var fn1 = new string();
	fn1 = fn.match(/[\/\\][^\/\\]*$/);
	///if(fn1!=null && fn1.length>0) fn = fn1;
	fn = fn.tolowercase();
	if(fn.search(/^.*\.ez$/)>=0) {
		return("application/andrew-inset"); }
	if(fn.search(/^.*\.ai$/)>=0) {
		return("application/illustrator"); }
	if(fn.search(/^.*\.nb$/)>=0) {
		return("application/mathematica"); }
	if(fn.search(/^.*\.bin$/)>=0) {
		return("application/octet-stream"); }
	if(fn.search(/^.*\.oda$/)>=0) {
		return("application/oda"); }
	if(fn.search(/^.*\.pdf$/)>=0) {
		return("application/pdf"); }
	if(fn.search(/^.*\.xspf$/)>=0) {
		return("application/xspf+xml"); }
	if(fn.search(/^.*\.pla$/)>=0) {
		return("audio/x-iriver-pla"); }
	if(fn.search(/^.*\.pgp$/)>=0) {
		return("application/pgp-encrypted"); }
	if(fn.search(/^.*\.gpg$/)>=0) {
		return("application/pgp-encrypted"); }
	if(fn.search(/^.*\.asc$/)>=0) {
		return("application/pgp-encrypted"); }
	if(fn.search(/^.*\.skr$/)>=0) {
		return("application/pgp-keys"); }
	if(fn.search(/^.*\.pkr$/)>=0) {
		return("application/pgp-keys"); }
	if(fn.search(/^.*\.asc$/)>=0) {
		return("application/pgp-keys"); }
	if(fn.search(/^.*\.p7s$/)>=0) {
		return("application/pkcs7-signature"); }
	if(fn.search(/^.*\.p10$/)>=0) {
		return("application/pkcs10"); }
	if(fn.search(/^.*\.ps$/)>=0) {
		return("application/postscript"); }
	if(fn.search(/^.*\.rtf$/)>=0) {
		return("application/rtf"); }
	if(fn.search(/^.*\.siv$/)>=0) {
		return("application/sieve"); }
	if(fn.search(/^.*\.smil$/)>=0) {
		return("application/smil"); }
	if(fn.search(/^.*\.smi$/)>=0) {
		return("application/smil"); }
	if(fn.search(/^.*\.sml$/)>=0) {
		return("application/smil"); }
	if(fn.search(/^.*\.kino$/)>=0) {
		return("application/smil"); }
	if(fn.search(/^.*\.sit$/)>=0) {
		return("application/stuffit"); }
	if(fn.search(/^.*\.ged$/)>=0) {
		return("application/x-gedcom"); }
	if(fn.search(/^.*\.gedcom$/)>=0) {
		return("application/x-gedcom"); }
	if(fn.search(/^.*\.flv$/)>=0) {
		return("application/x-flash-video"); }
	if(fn.search(/^.*\.sgf$/)>=0) {
		return("application/x-go-sgf"); }
	if(fn.search(/^.*\.xlf$/)>=0) {
		return("application/x-xliff"); }
	if(fn.search(/^.*\.xliff$/)>=0) {
		return("application/x-xliff"); }
	if(fn.search(/^.*\.cdr$/)>=0) {
		return("application/vnd.corel-draw"); }
	if(fn.search(/^.*\.hpgl$/)>=0) {
		return("application/vnd.hp-hpgl"); }
	if(fn.search(/^.*\.pcl$/)>=0) {
		return("application/vnd.hp-pcl"); }
	if(fn.search(/^.*\.123$/)>=0) {
		return("application/vnd.lotus-1-2-3"); }
	if(fn.search(/^.*\.wk1$/)>=0) {
		return("application/vnd.lotus-1-2-3"); }
	if(fn.search(/^.*\.wk3$/)>=0) {
		return("application/vnd.lotus-1-2-3"); }
	if(fn.search(/^.*\.wk4$/)>=0) {
		return("application/vnd.lotus-1-2-3"); }
	if(fn.search(/^.*\.wks$/)>=0) {
		return("application/vnd.lotus-1-2-3"); }
	if(fn.search(/^.*\.xul$/)>=0) {
		return("application/vnd.mozilla.xul+xml"); }
	if(fn.search(/^.*\.mdb$/)>=0) {
		return("application/vnd.ms-access"); }
	if(fn.search(/^.*\.xls$/)>=0) {
		return("application/vnd.ms-excel"); }
	if(fn.search(/^.*\.xlc$/)>=0) {
		return("application/vnd.ms-excel"); }
	if(fn.search(/^.*\.xll$/)>=0) {
		return("application/vnd.ms-excel"); }
	if(fn.search(/^.*\.xlm$/)>=0) {
		return("application/vnd.ms-excel"); }
	if(fn.search(/^.*\.xlw$/)>=0) {
		return("application/vnd.ms-excel"); }
	if(fn.search(/^.*\.xla$/)>=0) {
		return("application/vnd.ms-excel"); }
	if(fn.search(/^.*\.xlt$/)>=0) {
		return("application/vnd.ms-excel"); }
	if(fn.search(/^.*\.xld$/)>=0) {
		return("application/vnd.ms-excel"); }
	if(fn.search(/^.*\.ppz$/)>=0) {
		return("application/vnd.ms-powerpoint"); }
	if(fn.search(/^.*\.ppt$/)>=0) {
		return("application/vnd.ms-powerpoint"); }
	if(fn.search(/^.*\.pps$/)>=0) {
		return("application/vnd.ms-powerpoint"); }
	if(fn.search(/^.*\.pot$/)>=0) {
		return("application/vnd.ms-powerpoint"); }
	if(fn.search(/^.*\.xps$/)>=0) {
		return("application/vnd.ms-xpsdocument"); }
	if(fn.search(/^.*\.doc$/)>=0) {
		return("application/msword"); }
	if(fn.search(/^.*\.tnef$/)>=0) {
		return("application/vnd.ms-tnef"); }
	if(fn.search(/^.*\.tnf$/)>=0) {
		return("application/vnd.ms-tnef"); }
	if(fn.search(/^winmail\.dat$/)>=0) {
		return("application/vnd.ms-tnef"); }
	if(fn.search(/^.*\.sdc$/)>=0) {
		return("application/vnd.stardivision.calc"); }
	if(fn.search(/^.*\.sds$/)>=0) {
		return("application/vnd.stardivision.chart"); }
	if(fn.search(/^.*\.sda$/)>=0) {
		return("application/vnd.stardivision.draw"); }
	if(fn.search(/^.*\.sdd$/)>=0) {
		return("application/vnd.stardivision.impress"); }
	if(fn.search(/^.*\.sdp$/)>=0) {
		return("application/vnd.stardivision.impress"); }
	if(fn.search(/^.*\.smd$/)>=0) {
		return("application/vnd.stardivision.mail"); }
	if(fn.search(/^.*\.smf$/)>=0) {
		return("application/vnd.stardivision.math"); }
	if(fn.search(/^.*\.sdw$/)>=0) {
		return("application/vnd.stardivision.writer"); }
	if(fn.search(/^.*\.vor$/)>=0) {
		return("application/vnd.stardivision.writer"); }
	if(fn.search(/^.*\.sgl$/)>=0) {
		return("application/vnd.stardivision.writer"); }
	if(fn.search(/^.*\.sxc$/)>=0) {
		return("application/vnd.sun.xml.calc"); }
	if(fn.search(/^.*\.stc$/)>=0) {
		return("application/vnd.sun.xml.calc.template"); }
	if(fn.search(/^.*\.sxd$/)>=0) {
		return("application/vnd.sun.xml.draw"); }
	if(fn.search(/^.*\.std$/)>=0) {
		return("application/vnd.sun.xml.draw.template"); }
	if(fn.search(/^.*\.sxi$/)>=0) {
		return("application/vnd.sun.xml.impress"); }
	if(fn.search(/^.*\.sti$/)>=0) {
		return("application/vnd.sun.xml.impress.template"); }
	if(fn.search(/^.*\.sxm$/)>=0) {
		return("application/vnd.sun.xml.math"); }
	if(fn.search(/^.*\.sxw$/)>=0) {
		return("application/vnd.sun.xml.writer"); }
	if(fn.search(/^.*\.sxg$/)>=0) {
		return("application/vnd.sun.xml.writer.global"); }
	if(fn.search(/^.*\.stw$/)>=0) {
		return("application/vnd.sun.xml.writer.template"); }
	if(fn.search(/^.*\.odt$/)>=0) {
		return("application/vnd.oasis.opendocument.text"); }
	if(fn.search(/^.*\.ott$/)>=0) {
		return("application/vnd.oasis.opendocument.text-template"); }
	if(fn.search(/^.*\.oth$/)>=0) {
		return("application/vnd.oasis.opendocument.text-web"); }
	if(fn.search(/^.*\.odm$/)>=0) {
		return("application/vnd.oasis.opendocument.text-master"); }
	if(fn.search(/^.*\.odg$/)>=0) {
		return("application/vnd.oasis.opendocument.graphics"); }
	if(fn.search(/^.*\.otg$/)>=0) {
		return("application/vnd.oasis.opendocument.graphics-template"); }
	if(fn.search(/^.*\.odp$/)>=0) {
		return("application/vnd.oasis.opendocument.presentation"); }
	if(fn.search(/^.*\.otp$/)>=0) {
		return("application/vnd.oasis.opendocument.presentation-template"); }
	if(fn.search(/^.*\.ods$/)>=0) {
		return("application/vnd.oasis.opendocument.spreadsheet"); }
	if(fn.search(/^.*\.ots$/)>=0) {
		return("application/vnd.oasis.opendocument.spreadsheet-template"); }
	if(fn.search(/^.*\.odc$/)>=0) {
		return("application/vnd.oasis.opendocument.chart"); }
	if(fn.search(/^.*\.odf$/)>=0) {
		return("application/vnd.oasis.opendocument.formula"); }
	if(fn.search(/^.*\.odb$/)>=0) {
		return("application/vnd.oasis.opendocument.database"); }
	if(fn.search(/^.*\.odi$/)>=0) {
		return("application/vnd.oasis.opendocument.image"); }
	if(fn.search(/^.*\.sis$/)>=0) {
		return("application/vnd.symbian.install"); }
	if(fn.search(/^.*\.sisx$/)>=0) {
		return("x-epoc/x-sisx-app"); }
	if(fn.search(/^.*\.wp$/)>=0) {
		return("application/vnd.wordperfect"); }
	if(fn.search(/^.*\.wp4$/)>=0) {
		return("application/vnd.wordperfect"); }
	if(fn.search(/^.*\.wp5$/)>=0) {
		return("application/vnd.wordperfect"); }
	if(fn.search(/^.*\.wp6$/)>=0) {
		return("application/vnd.wordperfect"); }
	if(fn.search(/^.*\.wpd$/)>=0) {
		return("application/vnd.wordperfect"); }
	if(fn.search(/^.*\.wpp$/)>=0) {
		return("application/vnd.wordperfect"); }
	if(fn.search(/^.*\.xbel$/)>=0) {
		return("application/x-xbel"); }
	if(fn.search(/^.*\.7z$/)>=0) {
		return("application/x-7z-compressed"); }
	if(fn.search(/^.*\.abw$/)>=0) {
		return("application/x-abiword"); }
	if(fn.search(/^.*\.abw\.crashed$/)>=0) {
		return("application/x-abiword"); }
	if(fn.search(/^.*\.abw\.gz$/)>=0) {
		return("application/x-abiword"); }
	if(fn.search(/^.*\.zabw$/)>=0) {
		return("application/x-abiword"); }
	if(fn.search(/^.*\.cue$/)>=0) {
		return("application/x-cue"); }
	if(fn.search(/^.*\.sam$/)>=0) {
		return("application/x-amipro"); }
	if(fn.search(/^.*\.as$/)>=0) {
		return("application/x-applix-spreadsheet"); }
	if(fn.search(/^.*\.aw$/)>=0) {
		return("application/x-applix-word"); }
	if(fn.search(/^.*\.a$/)>=0) {
		return("application/x-archive"); }
	if(fn.search(/^.*\.arj$/)>=0) {
		return("application/x-arj"); }
	if(fn.search(/^.*\.asp$/)>=0) {
		return("application/x-asp"); }
	if(fn.search(/^.*\.bcpio$/)>=0) {
		return("application/x-bcpio"); }
	if(fn.search(/^.*\.torrent$/)>=0) {
		return("application/x-bittorrent"); }
	if(fn.search(/^.*\.blender$/)>=0) {
		return("application/x-blender"); }
	if(fn.search(/^.*\.blend$/)>=0) {
		return("application/x-blender"); }
	if(fn.search(/^.*\.blend$/)>=0) {
		return("application/x-blender"); }
	if(fn.search(/^.*\.dvi\.bz2$/)>=0) {
		return("application/x-bzdvi"); }
	if(fn.search(/^.*\.bz$/)>=0) {
		return("application/x-bzip"); }
	if(fn.search(/^.*\.bz2$/)>=0) {
		return("application/x-bzip"); }
	if(fn.search(/^.*\.tar\.bz$/)>=0) {
		return("application/x-bzip-compressed-tar"); }
	if(fn.search(/^.*\.tar\.bz2$/)>=0) {
		return("application/x-bzip-compressed-tar"); }
	if(fn.search(/^.*\.tbz$/)>=0) {
		return("application/x-bzip-compressed-tar"); }
	if(fn.search(/^.*\.tbz2$/)>=0) {
		return("application/x-bzip-compressed-tar"); }
	if(fn.search(/^.*\.pdf\.bz2$/)>=0) {
		return("application/x-bzpdf"); }
	if(fn.search(/^.*\.ps\.bz2$/)>=0) {
		return("application/x-bzpostscript"); }
	if(fn.search(/^.*\.cbr$/)>=0) {
		return("application/x-cbr"); }
	if(fn.search(/^.*\.cbz$/)>=0) {
		return("application/x-cbz"); }
	if(fn.search(/^.*\.iso$/)>=0) {
		return("application/x-cd-image"); }
	if(fn.search(/^.*\.iso9660$/)>=0) {
		return("application/x-cd-image"); }
	if(fn.search(/^.*\.cgi$/)>=0) {
		return("application/x-cgi"); }
	if(fn.search(/^.*\.pgn$/)>=0) {
		return("application/x-chess-pgn"); }
	if(fn.search(/^.*\.chm$/)>=0) {
		return("application/x-chm"); }
	if(fn.search(/^.*\.z$/)>=0) {
		return("application/x-compress"); }
	if(fn.search(/^.*\.tar\.gz$/)>=0) {
		return("application/x-compressed-tar"); }
	if(fn.search(/^.*\.tgz$/)>=0) {
		return("application/x-compressed-tar"); }
	if(fn.search(/^core$/)>=0) {
		return("application/x-core"); }
	if(fn.search(/^.*\.cpio$/)>=0) {
		return("application/x-cpio"); }
	if(fn.search(/^.*\.cpio\.gz$/)>=0) {
		return("application/x-cpio-compressed"); }
	if(fn.search(/^.*\.csh$/)>=0) {
		return("application/x-csh"); }
	if(fn.search(/^.*\.dbf$/)>=0) {
		return("application/x-dbf"); }
	if(fn.search(/^.*\.es$/)>=0) {
		return("application/ecmascript"); }
	if(fn.search(/^.*\.dc$/)>=0) {
		return("application/x-dc-rom"); }
	if(fn.search(/^.*\.nds$/)>=0) {
		return("application/x-nintendo-ds-rom"); }
	if(fn.search(/^.*\.deb$/)>=0) {
		return("application/x-deb"); }
	if(fn.search(/^.*\.ui$/)>=0) {
		return("application/x-designer"); }
	if(fn.search(/^.*\.desktop$/)>=0) {
		return("application/x-desktop"); }
	if(fn.search(/^.*\.kdelnk$/)>=0) {
		return("application/x-desktop"); }
	if(fn.search(/^.*\.dia$/)>=0) {
		return("application/x-dia-diagram"); }
	if(fn.search(/^.*\.dvi$/)>=0) {
		return("application/x-dvi"); }
	if(fn.search(/^.*\.etheme$/)>=0) {
		return("application/x-e-theme"); }
	if(fn.search(/^.*\.egon$/)>=0) {
		return("application/x-egon"); }
	if(fn.search(/^.*\.exe$/)>=0) {
		return("application/x-executable"); }
	if(fn.search(/^.*\.pfa$/)>=0) {
		return("application/x-font-type1"); }
	if(fn.search(/^.*\.pfb$/)>=0) {
		return("application/x-font-type1"); }
	if(fn.search(/^.*\.gsf$/)>=0) {
		return("application/x-font-type1"); }
	if(fn.search(/^.*\.afm$/)>=0) {
		return("application/x-font-afm"); }
	if(fn.search(/^.*\.bdf$/)>=0) {
		return("application/x-font-bdf"); }
	if(fn.search(/^.*\.psf$/)>=0) {
		return("application/x-font-linux-psf"); }
	if(fn.search(/^.*\.psf\.gz$/)>=0) {
		return("application/x-gz-font-linux-psf"); }
	if(fn.search(/^.*\.pcf$/)>=0) {
		return("application/x-font-pcf"); }
	if(fn.search(/^.*\.pcf\.z$/)>=0) {
		return("application/x-font-pcf"); }
	if(fn.search(/^.*\.pcf\.gz$/)>=0) {
		return("application/x-font-pcf"); }
	if(fn.search(/^.*\.spd$/)>=0) {
		return("application/x-font-speedo"); }
	if(fn.search(/^.*\.ttf$/)>=0) {
		return("application/x-font-ttf"); }
	if(fn.search(/^.*\.ttc$/)>=0) {
		return("application/x-font-ttf"); }
	if(fn.search(/^.*\.gb$/)>=0) {
		return("application/x-gameboy-rom"); }
	if(fn.search(/^.*\.gba$/)>=0) {
		return("application/x-gba-rom"); }
	if(fn.search(/^.*\.gen$/)>=0) {
		return("application/x-genesis-rom"); }
	if(fn.search(/^.*\.md$/)>=0) {
		return("application/x-genesis-rom"); }
	if(fn.search(/^.*\.gmo$/)>=0) {
		return("application/x-gettext-translation"); }
	if(fn.search(/^.*\.mo$/)>=0) {
		return("application/x-gettext-translation"); }
	if(fn.search(/^.*\.glade$/)>=0) {
		return("application/x-glade"); }
	if(fn.search(/^.*\.gnucash$/)>=0) {
		return("application/x-gnucash"); }
	if(fn.search(/^.*\.gnc$/)>=0) {
		return("application/x-gnucash"); }
	if(fn.search(/^.*\.xac$/)>=0) {
		return("application/x-gnucash"); }
	if(fn.search(/^.*\.gnumeric$/)>=0) {
		return("application/x-gnumeric"); }
	if(fn.search(/^.*\.gp$/)>=0) {
		return("application/x-gnuplot"); }
	if(fn.search(/^.*\.gplt$/)>=0) {
		return("application/x-gnuplot"); }
	if(fn.search(/^.*\.gnuplot$/)>=0) {
		return("application/x-gnuplot"); }
	if(fn.search(/^.*\.gra$/)>=0) {
		return("application/x-graphite"); }
	if(fn.search(/^.*\.dvi\.gz$/)>=0) {
		return("application/x-gzdvi"); }
	if(fn.search(/^.*\.gz$/)>=0) {
		return("application/x-gzip"); }
	if(fn.search(/^.*\.pdf\.gz$/)>=0) {
		return("application/x-gzpdf"); }
	if(fn.search(/^.*\.ps\.gz$/)>=0) {
		return("application/x-gzpostscript"); }
	if(fn.search(/^.*\.hdf$/)>=0) {
		return("application/x-hdf"); }
	if(fn.search(/^.*\.jar$/)>=0) {
		return("application/x-java-archive"); }
	if(fn.search(/^.*\.class$/)>=0) {
		return("application/x-java"); }
	if(fn.search(/^.*\.jnlp$/)>=0) {
		return("application/x-java-jnlp-file"); }
	if(fn.search(/^.*\.js$/)>=0) {
		return("application/javascript"); }
	if(fn.search(/^.*\.jpr$/)>=0) {
		return("application/x-jbuilder-project"); }
	if(fn.search(/^.*\.jpx$/)>=0) {
		return("application/x-jbuilder-project"); }
	if(fn.search(/^.*\.karbon$/)>=0) {
		return("application/x-karbon"); }
	if(fn.search(/^.*\.chrt$/)>=0) {
		return("application/x-kchart"); }
	if(fn.search(/^.*\.kfo$/)>=0) {
		return("application/x-kformula"); }
	if(fn.search(/^.*\.kil$/)>=0) {
		return("application/x-killustrator"); }
	if(fn.search(/^.*\.flw$/)>=0) {
		return("application/x-kivio"); }
	if(fn.search(/^.*\.kon$/)>=0) {
		return("application/x-kontour"); }
	if(fn.search(/^.*\.kpm$/)>=0) {
		return("application/x-kpovmodeler"); }
	if(fn.search(/^.*\.kpr$/)>=0) {
		return("application/x-kpresenter"); }
	if(fn.search(/^.*\.kpt$/)>=0) {
		return("application/x-kpresenter"); }
	if(fn.search(/^.*\.kra$/)>=0) {
		return("application/x-krita"); }
	if(fn.search(/^.*\.ksp$/)>=0) {
		return("application/x-kspread"); }
	if(fn.search(/^.*\.kud$/)>=0) {
		return("application/x-kugar"); }
	if(fn.search(/^.*\.kwd$/)>=0) {
		return("application/x-kword"); }
	if(fn.search(/^.*\.kwt$/)>=0) {
		return("application/x-kword"); }
	if(fn.search(/^.*\.lha$/)>=0) {
		return("application/x-lha"); }
	if(fn.search(/^.*\.lzh$/)>=0) {
		return("application/x-lha"); }
	if(fn.search(/^.*\.lhz$/)>=0) {
		return("application/x-lhz"); }
	if(fn.search(/^.*\.ts$/)>=0) {
		return("application/x-linguist"); }
	if(fn.search(/^.*\.lyx$/)>=0) {
		return("application/x-lyx"); }
	if(fn.search(/^.*\.lzo$/)>=0) {
		return("application/x-lzop"); }
	if(fn.search(/^.*\.mgp$/)>=0) {
		return("application/x-magicpoint"); }
	if(fn.search(/^.*\.mkv$/)>=0) {
		return("video/x-matroska"); }
	if(fn.search(/^.*\.mka$/)>=0) {
		return("audio/x-matroska"); }
	if(fn.search(/^.*\.ocl$/)>=0) {
		return("text/x-ocl"); }
	if(fn.search(/^.*\.mif$/)>=0) {
		return("application/x-mif"); }
	if(fn.search(/^.*\.exe$/)>=0) {
		return("application/x-ms-dos-executable"); }
	if(fn.search(/^.*\.wri$/)>=0) {
		return("application/x-mswrite"); }
	if(fn.search(/^.*\.msx$/)>=0) {
		return("application/x-msx-rom"); }
	if(fn.search(/^.*\.m4$/)>=0) {
		return("application/x-m4"); }
	if(fn.search(/^.*\.n64$/)>=0) {
		return("application/x-n64-rom"); }
	if(fn.search(/^.*\.nes$/)>=0) {
		return("application/x-nes-rom"); }
	if(fn.search(/^.*\.cdf$/)>=0) {
		return("application/x-netcdf"); }
	if(fn.search(/^.*\.nc$/)>=0) {
		return("application/x-netcdf"); }
	if(fn.search(/^.*\.o$/)>=0) {
		return("application/x-object"); }
	if(fn.search(/^.*\.ogg$/)>=0) {
		return("application/ogg"); }
	if(fn.search(/^.*\.ogx$/)>=0) {
		return("application/ogg"); }
	if(fn.search(/^.*\.oga$/)>=0) {
		return("audio/ogg"); }
	if(fn.search(/^.*\.ogv$/)>=0) {
		return("video/ogg"); }
	if(fn.search(/^.*\.ogg$/)>=0) {
		return("audio/x-vorbis+ogg"); }
	if(fn.search(/^.*\.ogg$/)>=0) {
		return("audio/x-flac+ogg"); }
	if(fn.search(/^.*\.ogg$/)>=0) {
		return("audio/x-speex+ogg"); }
	if(fn.search(/^.*\.spx$/)>=0) {
		return("audio/x-speex"); }
	if(fn.search(/^.*\.ogg$/)>=0) {
		return("video/x-theora+ogg"); }
	if(fn.search(/^.*\.ogm$/)>=0) {
		return("video/x-ogm+ogg"); }
	if(fn.search(/^.*\.oleo$/)>=0) {
		return("application/x-oleo"); }
	if(fn.search(/^.*\.pak$/)>=0) {
		return("application/x-pak"); }
	if(fn.search(/^.*\.pdb$/)>=0) {
		return("application/x-palm-database"); }
	if(fn.search(/^.*\.prc$/)>=0) {
		return("application/x-palm-database"); }
	if(fn.search(/^.*\.par2$/)>=0) {
		return("application/x-par2"); }
	if(fn.search(/^.*\.par2$/)>=0) {
		return("application/x-par2"); }
	if(fn.search(/^.*\.pl$/)>=0) {
		return("application/x-perl"); }
	if(fn.search(/^.*\.pm$/)>=0) {
		return("application/x-perl"); }
	if(fn.search(/^.*\.al$/)>=0) {
		return("application/x-perl"); }
	if(fn.search(/^.*\.perl$/)>=0) {
		return("application/x-perl"); }
	if(fn.search(/^.*\.php$/)>=0) {
		return("application/x-php"); }
	if(fn.search(/^.*\.php3$/)>=0) {
		return("application/x-php"); }
	if(fn.search(/^.*\.php4$/)>=0) {
		return("application/x-php"); }
	if(fn.search(/^.*\.p12$/)>=0) {
		return("application/x-pkcs12"); }
	if(fn.search(/^.*\.pfx$/)>=0) {
		return("application/x-pkcs12"); }
	if(fn.search(/^.*\.pln$/)>=0) {
		return("application/x-planperfect"); }
	if(fn.search(/^gmon\.out$/)>=0) {
		return("application/x-profile"); }
	if(fn.search(/^.*\.pw$/)>=0) {
		return("application/x-pw"); }
	if(fn.search(/^.*\.pyc$/)>=0) {
		return("application/x-python-bytecode"); }
	if(fn.search(/^.*\.pyo$/)>=0) {
		return("application/x-python-bytecode"); }
	if(fn.search(/^.*\.wb1$/)>=0) {
		return("application/x-quattropro"); }
	if(fn.search(/^.*\.wb2$/)>=0) {
		return("application/x-quattropro"); }
	if(fn.search(/^.*\.wb3$/)>=0) {
		return("application/x-quattropro"); }
	if(fn.search(/^.*\.qtl$/)>=0) {
		return("application/x-quicktime-media-link"); }
	if(fn.search(/^.*\.qif$/)>=0) {
		return("application/x-qw"); }
	if(fn.search(/^.*\.rar$/)>=0) {
		return("application/x-rar"); }
	if(fn.search(/^.*\.dar$/)>=0) {
		return("application/x-dar"); }
	if(fn.search(/^.*\.rej$/)>=0) {
		return("application/x-reject"); }
	if(fn.search(/^.*\.rpm$/)>=0) {
		return("application/x-rpm"); }
	if(fn.search(/^.*\.rb$/)>=0) {
		return("application/x-ruby"); }
	if(fn.search(/^.*\.mab$/)>=0) {
		return("application/x-markaby"); }
	if(fn.search(/^.*\.shar$/)>=0) {
		return("application/x-shar"); }
	if(fn.search(/^.*\.la$/)>=0) {
		return("application/x-shared-library-la"); }
	if(fn.search(/^.*\.so$/)>=0) {
		return("application/x-sharedlib"); }
	if(fn.search(/^.*\.sh$/)>=0) {
		return("application/x-shellscript"); }
	if(fn.search(/^.*\.swf$/)>=0) {
		return("application/x-shockwave-flash"); }
	if(fn.search(/^.*\.spl$/)>=0) {
		return("application/x-shockwave-flash"); }
	if(fn.search(/^.*\.shn$/)>=0) {
		return("application/x-shorten"); }
	if(fn.search(/^.*\.siag$/)>=0) {
		return("application/x-siag"); }
	if(fn.search(/^.*\.sms$/)>=0) {
		return("application/x-sms-rom"); }
	if(fn.search(/^.*\.gg$/)>=0) {
		return("application/x-sms-rom"); }
	if(fn.search(/^.*\.smc$/)>=0) {
		return("application/x-snes-rom"); }
	if(fn.search(/^.*\.srt$/)>=0) {
		return("application/x-subrip"); }
	if(fn.search(/^.*\.smi$/)>=0) {
		return("application/x-sami"); }
	if(fn.search(/^.*\.sami$/)>=0) {
		return("application/x-sami"); }
	if(fn.search(/^.*\.sub$/)>=0) {
		return("text/x-microdvd"); }
	if(fn.search(/^.*\.sub$/)>=0) {
		return("text/x-mpsub"); }
	if(fn.search(/^.*\.ssa$/)>=0) {
		return("text/x-ssa"); }
	if(fn.search(/^.*\.ass$/)>=0) {
		return("text/x-ssa"); }
	if(fn.search(/^.*\.sv4cpio$/)>=0) {
		return("application/x-sv4cpio"); }
	if(fn.search(/^.*\.sv4crc$/)>=0) {
		return("application/x-sv4crc"); }
	if(fn.search(/^.*\.tar$/)>=0) {
		return("application/x-tar"); }
	if(fn.search(/^.*\.gtar$/)>=0) {
		return("application/x-tar"); }
	if(fn.search(/^.*\.tar\.z$/)>=0) {
		return("application/x-tarz"); }
	if(fn.search(/^.*\.gf$/)>=0) {
		return("application/x-tex-gf"); }
	if(fn.search(/^.*\.pk$/)>=0) {
		return("application/x-tex-pk"); }
	if(fn.search(/^.*\.obj$/)>=0) {
		return("application/x-tgif"); }
	if(fn.search(/^.*\.theme$/)>=0) {
		return("application/x-theme"); }
	if(fn.search(/^.*~$/)>=0) {
		return("application/x-trash"); }
	if(fn.search(/^.*%$/)>=0) {
		return("application/x-trash"); }
	if(fn.search(/^.*\.bak$/)>=0) {
		return("application/x-trash"); }
	if(fn.search(/^.*\.old$/)>=0) {
		return("application/x-trash"); }
	if(fn.search(/^.*\.sik$/)>=0) {
		return("application/x-trash"); }
	if(fn.search(/^.*\.tr$/)>=0) {
		return("text/troff"); }
	if(fn.search(/^.*\.roff$/)>=0) {
		return("text/troff"); }
	if(fn.search(/^.*\.t$/)>=0) {
		return("text/troff"); }
	if(fn.search(/^.*\.man$/)>=0) {
		return("application/x-troff-man"); }
	if(fn.search(/^.*\.tar\.lzo$/)>=0) {
		return("application/x-tzo"); }
	if(fn.search(/^.*\.tzo$/)>=0) {
		return("application/x-tzo"); }
	if(fn.search(/^.*\.ustar$/)>=0) {
		return("application/x-ustar"); }
	if(fn.search(/^.*\.src$/)>=0) {
		return("application/x-wais-source"); }
	if(fn.search(/^.*\.wpg$/)>=0) {
		return("application/x-wpg"); }
	if(fn.search(/^.*\.der$/)>=0) {
		return("application/x-x509-ca-cert"); }
	if(fn.search(/^.*\.cer$/)>=0) {
		return("application/x-x509-ca-cert"); }
	if(fn.search(/^.*\.crt$/)>=0) {
		return("application/x-x509-ca-cert"); }
	if(fn.search(/^.*\.cert$/)>=0) {
		return("application/x-x509-ca-cert"); }
	if(fn.search(/^.*\.pem$/)>=0) {
		return("application/x-x509-ca-cert"); }
	if(fn.search(/^.*\.zoo$/)>=0) {
		return("application/x-zoo"); }
	if(fn.search(/^.*\.xhtml$/)>=0) {
		return("application/xhtml+xml"); }
	if(fn.search(/^.*\.zip$/)>=0) {
		return("application/zip"); }
	if(fn.search(/^.*\.ac3$/)>=0) {
		return("audio/ac3"); }
	if(fn.search(/^.*\.amr$/)>=0) {
		return("audio/amr"); }
	if(fn.search(/^.*\.awb$/)>=0) {
		return("audio/amr-wb"); }
	if(fn.search(/^.*\.au$/)>=0) {
		return("audio/basic"); }
	if(fn.search(/^.*\.snd$/)>=0) {
		return("audio/basic"); }
	if(fn.search(/^.*\.sid$/)>=0) {
		return("audio/prs.sid"); }
	if(fn.search(/^.*\.psid$/)>=0) {
		return("audio/prs.sid"); }
	if(fn.search(/^.*\.aiff$/)>=0) {
		return("audio/x-aiff"); }
	if(fn.search(/^.*\.aif$/)>=0) {
		return("audio/x-aiff"); }
	if(fn.search(/^.*\.aifc$/)>=0) {
		return("audio/x-aiff"); }
	if(fn.search(/^.*\.ape$/)>=0) {
		return("audio/x-ape"); }
	if(fn.search(/^.*\.it$/)>=0) {
		return("audio/x-it"); }
	if(fn.search(/^.*\.flac$/)>=0) {
		return("audio/x-flac"); }
	if(fn.search(/^.*\.wv$/)>=0) {
		return("audio/x-wavpack"); }
	if(fn.search(/^.*\.wvp$/)>=0) {
		return("audio/x-wavpack"); }
	if(fn.search(/^.*\.wvc$/)>=0) {
		return("audio/x-wavpack-correction"); }
	if(fn.search(/^.*\.mid$/)>=0) {
		return("audio/midi"); }
	if(fn.search(/^.*\.midi$/)>=0) {
		return("audio/midi"); }
	if(fn.search(/^.*\.kar$/)>=0) {
		return("audio/midi"); }
	if(fn.search(/^.*\.m4a$/)>=0) {
		return("audio/mp4"); }
	if(fn.search(/^.*\.aac$/)>=0) {
		return("audio/mp4"); }
	if(fn.search(/^.*\.mp4$/)>=0) {
		return("video/mp4"); }
	if(fn.search(/^.*\.m4v$/)>=0) {
		return("video/mp4"); }
	if(fn.search(/^.*\.m4b$/)>=0) {
		return("audio/x-m4b"); }
	if(fn.search(/^.*\.3gp$/)>=0) {
		return("video/3gpp"); }
	if(fn.search(/^.*\.3gpp$/)>=0) {
		return("video/3gpp"); }
	if(fn.search(/^.*\.amr$/)>=0) {
		return("video/3gpp"); }
	if(fn.search(/^.*\.mod$/)>=0) {
		return("audio/x-mod"); }
	if(fn.search(/^.*\.ult$/)>=0) {
		return("audio/x-mod"); }
	if(fn.search(/^.*\.uni$/)>=0) {
		return("audio/x-mod"); }
	if(fn.search(/^.*\.m15$/)>=0) {
		return("audio/x-mod"); }
	if(fn.search(/^.*\.mtm$/)>=0) {
		return("audio/x-mod"); }
	if(fn.search(/^.*\.669$/)>=0) {
		return("audio/x-mod"); }
	if(fn.search(/^.*\.mp2$/)>=0) {
		return("audio/mp2"); }
	if(fn.search(/^.*\.mp3$/)>=0) {
		return("audio/mpeg"); }
	if(fn.search(/^.*\.mpga$/)>=0) {
		return("audio/mpeg"); }
	if(fn.search(/^.*\.m3u$/)>=0) {
		return("audio/x-mpegurl"); }
	if(fn.search(/^.*\.vlc$/)>=0) {
		return("audio/x-mpegurl"); }
	if(fn.search(/^.*\.asx$/)>=0) {
		return("audio/x-ms-asx"); }
	if(fn.search(/^.*\.wax$/)>=0) {
		return("audio/x-ms-asx"); }
	if(fn.search(/^.*\.wvx$/)>=0) {
		return("audio/x-ms-asx"); }
	if(fn.search(/^.*\.wmx$/)>=0) {
		return("audio/x-ms-asx"); }
	if(fn.search(/^.*\.psf$/)>=0) {
		return("audio/x-psf"); }
	if(fn.search(/^.*\.minipsf$/)>=0) {
		return("audio/x-minipsf"); }
	if(fn.search(/^.*\.psflib$/)>=0) {
		return("audio/x-psflib"); }
	if(fn.search(/^.*\.wma$/)>=0) {
		return("audio/x-ms-wma"); }
	if(fn.search(/^.*\.mpc$/)>=0) {
		return("audio/x-musepack"); }
	if(fn.search(/^.*\.mpp$/)>=0) {
		return("audio/x-musepack"); }
	if(fn.search(/^.*\.mp[+]$/)>=0) {
		return("audio/x-musepack"); }
	if(fn.search(/^.*\.ra$/)>=0) {
		return("audio/vnd.rn-realaudio"); }
	if(fn.search(/^.*\.rax$/)>=0) {
		return("audio/vnd.rn-realaudio"); }
	if(fn.search(/^.*\.ram$/)>=0) {
		return("application/ram"); }
	if(fn.search(/^.*\.rv$/)>=0) {
		return("video/vnd.rn-realvideo"); }
	if(fn.search(/^.*\.rvx$/)>=0) {
		return("video/vnd.rn-realvideo"); }
	if(fn.search(/^.*\.rm$/)>=0) {
		return("application/vnd.rn-realmedia"); }
	if(fn.search(/^.*\.rmj$/)>=0) {
		return("application/vnd.rn-realmedia"); }
	if(fn.search(/^.*\.rmm$/)>=0) {
		return("application/vnd.rn-realmedia"); }
	if(fn.search(/^.*\.rms$/)>=0) {
		return("application/vnd.rn-realmedia"); }
	if(fn.search(/^.*\.rmx$/)>=0) {
		return("application/vnd.rn-realmedia"); }
	if(fn.search(/^.*\.rmvb$/)>=0) {
		return("application/vnd.rn-realmedia"); }
	if(fn.search(/^.*\.rp$/)>=0) {
		return("image/vnd.rn-realpix"); }
	if(fn.search(/^.*\.rt$/)>=0) {
		return("text/vnd.rn-realtext"); }
	if(fn.search(/^.*\.s3m$/)>=0) {
		return("audio/x-s3m"); }
	if(fn.search(/^.*\.pls$/)>=0) {
		return("audio/x-scpls"); }
	if(fn.search(/^.*\.stm$/)>=0) {
		return("audio/x-stm"); }
	if(fn.search(/^.*\.voc$/)>=0) {
		return("audio/x-voc"); }
	if(fn.search(/^.*\.wav$/)>=0) {
		return("audio/x-wav"); }
	if(fn.search(/^.*\.xi$/)>=0) {
		return("audio/x-xi"); }
	if(fn.search(/^.*\.xm$/)>=0) {
		return("audio/x-xm"); }
	if(fn.search(/^.*\.tta$/)>=0) {
		return("audio/x-tta"); }
	if(fn.search(/^.*\.bmp$/)>=0) {
		return("image/bmp"); }
	if(fn.search(/^.*\.wbmp$/)>=0) {
		return("image/vnd.wap.wbmp"); }
	if(fn.search(/^.*\.cgm$/)>=0) {
		return("image/cgm"); }
	if(fn.search(/^.*\.g3$/)>=0) {
		return("image/fax-g3"); }
	if(fn.search(/^.*\.gif$/)>=0) {
		return("image/gif"); }
	if(fn.search(/^.*\.ief$/)>=0) {
		return("image/ief"); }
	if(fn.search(/^.*\.jpeg$/)>=0) {
		return("image/jpeg"); }
	if(fn.search(/^.*\.jpg$/)>=0) {
		return("image/jpeg"); }
	if(fn.search(/^.*\.jpe$/)>=0) {
		return("image/jpeg"); }
	if(fn.search(/^.*\.jp2$/)>=0) {
		return("image/jp2"); }
	if(fn.search(/^.*\.jpc$/)>=0) {
		return("image/jp2"); }
	if(fn.search(/^.*\.jpx$/)>=0) {
		return("image/jp2"); }
	if(fn.search(/^.*\.j2k$/)>=0) {
		return("image/jp2"); }
	if(fn.search(/^.*\.jpf$/)>=0) {
		return("image/jp2"); }
	if(fn.search(/^.*\.dds$/)>=0) {
		return("image/x-dds"); }
	if(fn.search(/^.*\.pict$/)>=0) {
		return("image/x-pict"); }
	if(fn.search(/^.*\.pict1$/)>=0) {
		return("image/x-pict"); }
	if(fn.search(/^.*\.pict2$/)>=0) {
		return("image/x-pict"); }
	if(fn.search(/^.*\.ufraw$/)>=0) {
		return("application/x-ufraw"); }
	if(fn.search(/^.*\.dng$/)>=0) {
		return("image/x-adobe-dng"); }
	if(fn.search(/^.*\.crw$/)>=0) {
		return("image/x-canon-crw"); }
	if(fn.search(/^.*\.cr2$/)>=0) {
		return("image/x-canon-cr2"); }
	if(fn.search(/^.*\.raf$/)>=0) {
		return("image/x-fuji-raf"); }
	if(fn.search(/^.*\.dcr$/)>=0) {
		return("image/x-kodak-dcr"); }
	if(fn.search(/^.*\.k25$/)>=0) {
		return("image/x-kodak-k25"); }
	if(fn.search(/^.*\.kdc$/)>=0) {
		return("image/x-kodak-kdc"); }
	if(fn.search(/^.*\.mrw$/)>=0) {
		return("image/x-minolta-mrw"); }
	if(fn.search(/^.*\.nef$/)>=0) {
		return("image/x-nikon-nef"); }
	if(fn.search(/^.*\.orf$/)>=0) {
		return("image/x-olympus-orf"); }
	if(fn.search(/^.*\.raw$/)>=0) {
		return("image/x-panasonic-raw"); }
	if(fn.search(/^.*\.pef$/)>=0) {
		return("image/x-pentax-pef"); }
	if(fn.search(/^.*\.x3f$/)>=0) {
		return("image/x-sigma-x3f"); }
	if(fn.search(/^.*\.srf$/)>=0) {
		return("image/x-sony-srf"); }
	if(fn.search(/^.*\.sr2$/)>=0) {
		return("image/x-sony-sr2"); }
	if(fn.search(/^.*\.arw$/)>=0) {
		return("image/x-sony-arw"); }
	if(fn.search(/^.*\.png$/)>=0) {
		return("image/png"); }
	if(fn.search(/^.*\.rle$/)>=0) {
		return("image/rle"); }
	if(fn.search(/^.*\.svg$/)>=0) {
		return("image/svg+xml"); }
	if(fn.search(/^.*\.svgz$/)>=0) {
		return("image/svg+xml-compressed"); }
	if(fn.search(/^.*\.tif$/)>=0) {
		return("image/tiff"); }
	if(fn.search(/^.*\.tiff$/)>=0) {
		return("image/tiff"); }
	if(fn.search(/^.*\.dwg$/)>=0) {
		return("image/vnd.dwg"); }
	if(fn.search(/^.*\.dxf$/)>=0) {
		return("image/vnd.dxf"); }
	if(fn.search(/^.*\.3ds$/)>=0) {
		return("image/x-3ds"); }
	if(fn.search(/^.*\.ag$/)>=0) {
		return("image/x-applix-graphics"); }
	if(fn.search(/^.*\.eps\.bz2$/)>=0) {
		return("image/x-bzeps"); }
	if(fn.search(/^.*\.epsi\.bz2$/)>=0) {
		return("image/x-bzeps"); }
	if(fn.search(/^.*\.epsf\.bz2$/)>=0) {
		return("image/x-bzeps"); }
	if(fn.search(/^.*\.ras$/)>=0) {
		return("image/x-cmu-raster"); }
	if(fn.search(/^.*\.xcf\.gz$/)>=0) {
		return("image/x-compressed-xcf"); }
	if(fn.search(/^.*\.xcf\.bz2$/)>=0) {
		return("image/x-compressed-xcf"); }
	if(fn.search(/^.*\.dcm$/)>=0) {
		return("application/dicom"); }
	if(fn.search(/^.*\.docbook$/)>=0) {
		return("application/docbook+xml"); }
	if(fn.search(/^.*\.djvu$/)>=0) {
		return("image/vnd.djvu"); }
	if(fn.search(/^.*\.djv$/)>=0) {
		return("image/vnd.djvu"); }
	if(fn.search(/^.*\.eps$/)>=0) {
		return("image/x-eps"); }
	if(fn.search(/^.*\.epsi$/)>=0) {
		return("image/x-eps"); }
	if(fn.search(/^.*\.epsf$/)>=0) {
		return("image/x-eps"); }
	if(fn.search(/^.*\.fits$/)>=0) {
		return("image/x-fits"); }
	if(fn.search(/^.*\.eps\.gz$/)>=0) {
		return("image/x-gzeps"); }
	if(fn.search(/^.*\.epsi\.gz$/)>=0) {
		return("image/x-gzeps"); }
	if(fn.search(/^.*\.epsf\.gz$/)>=0) {
		return("image/x-gzeps"); }
	if(fn.search(/^.*\.ico$/)>=0) {
		return("image/x-ico"); }
	if(fn.search(/^.*\.icns$/)>=0) {
		return("image/x-icns"); }
	if(fn.search(/^.*\.iff$/)>=0) {
		return("image/x-iff"); }
	if(fn.search(/^.*\.ilbm$/)>=0) {
		return("image/x-ilbm"); }
	if(fn.search(/^.*\.jng$/)>=0) {
		return("image/x-jng"); }
	if(fn.search(/^.*\.lwo$/)>=0) {
		return("image/x-lwo"); }
	if(fn.search(/^.*\.lwob$/)>=0) {
		return("image/x-lwo"); }
	if(fn.search(/^.*\.lws$/)>=0) {
		return("image/x-lws"); }
	if(fn.search(/^.*\.pntg$/)>=0) {
		return("image/x-macpaint"); }
	if(fn.search(/^.*\.msod$/)>=0) {
		return("image/x-msod"); }
	if(fn.search(/^.*\.pcd$/)>=0) {
		return("image/x-photo-cd"); }
	if(fn.search(/^.*\.pnm$/)>=0) {
		return("image/x-portable-anymap"); }
	if(fn.search(/^.*\.pbm$/)>=0) {
		return("image/x-portable-bitmap"); }
	if(fn.search(/^.*\.pgm$/)>=0) {
		return("image/x-portable-graymap"); }
	if(fn.search(/^.*\.ppm$/)>=0) {
		return("image/x-portable-pixmap"); }
	if(fn.search(/^.*\.psd$/)>=0) {
		return("image/x-psd"); }
	if(fn.search(/^.*\.rgb$/)>=0) {
		return("image/x-rgb"); }
	if(fn.search(/^.*\.sgi$/)>=0) {
		return("image/x-sgi"); }
	if(fn.search(/^.*\.sun$/)>=0) {
		return("image/x-sun-raster"); }
	if(fn.search(/^.*\.icb$/)>=0) {
		return("image/x-tga"); }
	if(fn.search(/^.*\.tga$/)>=0) {
		return("image/x-tga"); }
	if(fn.search(/^.*\.tpic$/)>=0) {
		return("image/x-tga"); }
	if(fn.search(/^.*\.vda$/)>=0) {
		return("image/x-tga"); }
	if(fn.search(/^.*\.vst$/)>=0) {
		return("image/x-tga"); }
	if(fn.search(/^.*\.cur$/)>=0) {
		return("image/x-win-bitmap"); }
	if(fn.search(/^.*\.emf$/)>=0) {
		return("image/x-emf"); }
	if(fn.search(/^.*\.wmf$/)>=0) {
		return("image/x-wmf"); }
	if(fn.search(/^.*\.xbm$/)>=0) {
		return("image/x-xbitmap"); }
	if(fn.search(/^.*\.xcf$/)>=0) {
		return("image/x-xcf"); }
	if(fn.search(/^.*\.fig$/)>=0) {
		return("image/x-xfig"); }
	if(fn.search(/^.*\.xpm$/)>=0) {
		return("image/x-xpixmap"); }
	if(fn.search(/^.*\.xwd$/)>=0) {
		return("image/x-xwindowdump"); }
	if(fn.search(/^rmail$/)>=0) {
		return("message/x-gnu-rmail"); }
	if(fn.search(/^.*\.wrl$/)>=0) {
		return("model/vrml"); }
	if(fn.search(/^.*\.vcs$/)>=0) {
		return("text/calendar"); }
	if(fn.search(/^.*\.ics$/)>=0) {
		return("text/calendar"); }
	if(fn.search(/^.*\.css$/)>=0) {
		return("text/css"); }
	if(fn.search(/^.*\.cssl$/)>=0) {
		return("text/css"); }
	if(fn.search(/^.*\.vcf$/)>=0) {
		return("text/directory"); }
	if(fn.search(/^.*\.vct$/)>=0) {
		return("text/directory"); }
	if(fn.search(/^.*\.gcrd$/)>=0) {
		return("text/directory"); }
	if(fn.search(/^.*\.t2t$/)>=0) {
		return("text/x-txt2tags"); }
	if(fn.search(/^.*\.vhd$/)>=0) {
		return("text/x-vhdl"); }
	if(fn.search(/^.*\.vhdl$/)>=0) {
		return("text/x-vhdl"); }
	if(fn.search(/^.*\.mml$/)>=0) {
		return("text/mathml"); }
	if(fn.search(/^.*\.txt$/)>=0) {
		return("text/plain"); }
	if(fn.search(/^.*\.asc$/)>=0) {
		return("text/plain"); }
	if(fn.search(/^.*\.rdf$/)>=0) {
		return("text/rdf"); }
	if(fn.search(/^.*\.rdfs$/)>=0) {
		return("text/rdf"); }
	if(fn.search(/^.*\.owl$/)>=0) {
		return("text/rdf"); }
	if(fn.search(/^.*\.rtx$/)>=0) {
		return("text/richtext"); }
	if(fn.search(/^.*\.rss$/)>=0) {
		return("application/rss+xml"); }
	if(fn.search(/^.*\.atom$/)>=0) {
		return("application/atom+xml"); }
	if(fn.search(/^.*\.opml$/)>=0) {
		return("text/x-opml+xml"); }
	if(fn.search(/^.*\.sgml$/)>=0) {
		return("text/sgml"); }
	if(fn.search(/^.*\.sgm$/)>=0) {
		return("text/sgml"); }
	if(fn.search(/^.*\.sylk$/)>=0) {
		return("text/spreadsheet"); }
	if(fn.search(/^.*\.slk$/)>=0) {
		return("text/spreadsheet"); }
	if(fn.search(/^.*\.tsv$/)>=0) {
		return("text/tab-separated-values"); }
	if(fn.search(/^.*\.jad$/)>=0) {
		return("text/vnd.sun.j2me.app-descriptor"); }
	if(fn.search(/^.*\.wml$/)>=0) {
		return("text/vnd.wap.wml"); }
	if(fn.search(/^.*\.wmls$/)>=0) {
		return("text/vnd.wap.wmlscript"); }
	if(fn.search(/^.*\.ace$/)>=0) {
		return("application/x-ace"); }
	if(fn.search(/^.*\.adb$/)>=0) {
		return("text/x-adasrc"); }
	if(fn.search(/^.*\.ads$/)>=0) {
		return("text/x-adasrc"); }
	if(fn.search(/^authors$/)>=0) {
		return("text/x-authors"); }
	if(fn.search(/^.*\.bib$/)>=0) {
		return("text/x-bibtex"); }
	if(fn.search(/^.*\.hh$/)>=0) {
		return("text/x-c++hdr"); }
	if(fn.search(/^.*\.hp$/)>=0) {
		return("text/x-c++hdr"); }
	if(fn.search(/^.*\.hpp$/)>=0) {
		return("text/x-c++hdr"); }
	if(fn.search(/^.*\.h[+][+]$/)>=0) {
		return("text/x-c++hdr"); }
	if(fn.search(/^.*\.hxx$/)>=0) {
		return("text/x-c++hdr"); }
	if(fn.search(/^.*\.cpp$/)>=0) {
		return("text/x-c++src"); }
	if(fn.search(/^.*\.cxx$/)>=0) {
		return("text/x-c++src"); }
	if(fn.search(/^.*\.cc$/)>=0) {
		return("text/x-c++src"); }
	if(fn.search(/^.*\.c$/)>=0) {
		return("text/x-c++src"); }
	if(fn.search(/^.*\.c[+][+]$/)>=0) {
		return("text/x-c++src"); }
	if(fn.search(/^changelog$/)>=0) {
		return("text/x-changelog"); }
	if(fn.search(/^.*\.h$/)>=0) {
		return("text/x-chdr"); }
	if(fn.search(/^.*\.csv$/)>=0) {
		return("text/csv"); }
	if(fn.search(/^copying$/)>=0) {
		return("text/x-copying"); }
	if(fn.search(/^credits$/)>=0) {
		return("text/x-credits"); }
	if(fn.search(/^.*\.c$/)>=0) {
		return("text/x-csrc"); }
	if(fn.search(/^.*\.cs$/)>=0) {
		return("text/x-csharp"); }
	if(fn.search(/^.*\.vala$/)>=0) {
		return("text/x-vala"); }
	if(fn.search(/^.*\.dcl$/)>=0) {
		return("text/x-dcl"); }
	if(fn.search(/^.*\.dsl$/)>=0) {
		return("text/x-dsl"); }
	if(fn.search(/^.*\.d$/)>=0) {
		return("text/x-dsrc"); }
	if(fn.search(/^.*\.dtd$/)>=0) {
		return("text/x-dtd"); }
	if(fn.search(/^.*\.el$/)>=0) {
		return("text/x-emacs-lisp"); }
	if(fn.search(/^.*\.erl$/)>=0) {
		return("text/x-erlang"); }
	if(fn.search(/^.*\.[ff]$/)>=0) {
		return("text/x-fortran"); }
	if(fn.search(/^.*\.[ff]9[05]$/)>=0) {
		return("text/x-fortran"); }
	if(fn.search(/^.*\.for$/)>=0) {
		return("text/x-fortran"); }
	if(fn.search(/^.*\.po$/)>=0) {
		return("text/x-gettext-translation"); }
	if(fn.search(/^.*\.pot$/)>=0) {
		return("text/x-gettext-translation-template"); }
	if(fn.search(/^.*\.html$/)>=0) {
		return("text/html"); }
	if(fn.search(/^.*\.htm$/)>=0) {
		return("text/html"); }
	if(fn.search(/^gtkrc$/)>=0) {
		return("text/x-gtkrc"); }
	if(fn.search(/^\.gtkrc$/)>=0) {
		return("text/x-gtkrc"); }
	if(fn.search(/^.*\.gvp$/)>=0) {
		return("text/x-google-video-pointer"); }
	if(fn.search(/^.*\.hs$/)>=0) {
		return("text/x-haskell"); }
	if(fn.search(/^.*\.idl$/)>=0) {
		return("text/x-idl"); }
	if(fn.search(/^install$/)>=0) {
		return("text/x-install"); }
	if(fn.search(/^.*\.java$/)>=0) {
		return("text/x-java"); }
	if(fn.search(/^.*\.ldif$/)>=0) {
		return("text/x-ldif"); }
	if(fn.search(/^.*\.lhs$/)>=0) {
		return("text/x-literate-haskell"); }
	if(fn.search(/^.*\.log$/)>=0) {
		return("text/x-log"); }
	if(fn.search(/^[mm]akefile$/)>=0) {
		return("text/x-makefile"); }
	if(fn.search(/^gnumakefile$/)>=0) {
		return("text/x-makefile"); }
	if(fn.search(/^.*\.moc$/)>=0) {
		return("text/x-moc"); }
	if(fn.search(/^.*\.mup$/)>=0) {
		return("text/x-mup"); }
	if(fn.search(/^.*\.not$/)>=0) {
		return("text/x-mup"); }
	if(fn.search(/^.*\.m$/)>=0) {
		return("text/x-objcsrc"); }
	if(fn.search(/^.*\.ml$/)>=0) {
		return("text/x-ocaml"); }
	if(fn.search(/^.*\.mli$/)>=0) {
		return("text/x-ocaml"); }
	if(fn.search(/^.*\.m$/)>=0) {
		return("text/x-matlab"); }
	if(fn.search(/^.*\.p$/)>=0) {
		return("text/x-pascal"); }
	if(fn.search(/^.*\.pas$/)>=0) {
		return("text/x-pascal"); }
	if(fn.search(/^.*\.diff$/)>=0) {
		return("text/x-patch"); }
	if(fn.search(/^.*\.patch$/)>=0) {
		return("text/x-patch"); }
	if(fn.search(/^.*\.py$/)>=0) {
		return("text/x-python"); }
	if(fn.search(/^.*\.lua$/)>=0) {
		return("text/x-lua"); }
	if(fn.search(/^readme*$/)>=0) {
		return("text/x-readme"); }
	if(fn.search(/^.*\.nfo$/)>=0) {
		return("text/x-readme"); }
	if(fn.search(/^.*\.spec$/)>=0) {
		return("text/x-rpm-spec"); }
	if(fn.search(/^.*\.scm$/)>=0) {
		return("text/x-scheme"); }
	if(fn.search(/^.*\.etx$/)>=0) {
		return("text/x-setext"); }
	if(fn.search(/^.*\.sql$/)>=0) {
		return("text/x-sql"); }
	if(fn.search(/^.*\.tcl$/)>=0) {
		return("text/x-tcl"); }
	if(fn.search(/^.*\.tk$/)>=0) {
		return("text/x-tcl"); }
	if(fn.search(/^.*\.tex$/)>=0) {
		return("text/x-tex"); }
	if(fn.search(/^.*\.ltx$/)>=0) {
		return("text/x-tex"); }
	if(fn.search(/^.*\.sty$/)>=0) {
		return("text/x-tex"); }
	if(fn.search(/^.*\.cls$/)>=0) {
		return("text/x-tex"); }
	if(fn.search(/^.*\.dtx$/)>=0) {
		return("text/x-tex"); }
	if(fn.search(/^.*\.ins$/)>=0) {
		return("text/x-tex"); }
	if(fn.search(/^.*\.latex$/)>=0) {
		return("text/x-tex"); }
	if(fn.search(/^.*\.texi$/)>=0) {
		return("text/x-texinfo"); }
	if(fn.search(/^.*\.texinfo$/)>=0) {
		return("text/x-texinfo"); }
	if(fn.search(/^.*\.me$/)>=0) {
		return("text/x-troff-me"); }
	if(fn.search(/^.*\.mm$/)>=0) {
		return("text/x-troff-mm"); }
	if(fn.search(/^.*\.ms$/)>=0) {
		return("text/x-troff-ms"); }
	if(fn.search(/^.*\.uil$/)>=0) {
		return("text/x-uil"); }
	if(fn.search(/^.*\.uri$/)>=0) {
		return("text/x-uri"); }
	if(fn.search(/^.*\.url$/)>=0) {
		return("text/x-uri"); }
	if(fn.search(/^.*\.xmi$/)>=0) {
		return("text/x-xmi"); }
	if(fn.search(/^.*\.fo$/)>=0) {
		return("text/x-xslfo"); }
	if(fn.search(/^.*\.xslfo$/)>=0) {
		return("text/x-xslfo"); }
	if(fn.search(/^.*\.xml$/)>=0) {
		return("application/xml"); }
	if(fn.search(/^.*\.xsl$/)>=0) {
		return("application/xml"); }
	if(fn.search(/^.*\.xslt$/)>=0) {
		return("application/xml"); }
	if(fn.search(/^.*\.xbl$/)>=0) {
		return("application/xml"); }
	if(fn.search(/^.*\.dv$/)>=0) {
		return("video/dv"); }
	if(fn.search(/^.*\.mpeg$/)>=0) {
		return("video/mpeg"); }
	if(fn.search(/^.*\.mpg$/)>=0) {
		return("video/mpeg"); }
	if(fn.search(/^.*\.mp2$/)>=0) {
		return("video/mpeg"); }
	if(fn.search(/^.*\.mpe$/)>=0) {
		return("video/mpeg"); }
	if(fn.search(/^.*\.vob$/)>=0) {
		return("video/mpeg"); }
	if(fn.search(/^.*\.m2t$/)>=0) {
		return("video/mpeg"); }
	if(fn.search(/^.*\.qt$/)>=0) {
		return("video/quicktime"); }
	if(fn.search(/^.*\.mov$/)>=0) {
		return("video/quicktime"); }
	if(fn.search(/^.*\.moov$/)>=0) {
		return("video/quicktime"); }
	if(fn.search(/^.*\.qtvr$/)>=0) {
		return("video/quicktime"); }
	if(fn.search(/^.*\.qtif$/)>=0) {
		return("image/x-quicktime"); }
	if(fn.search(/^.*\.qif$/)>=0) {
		return("image/x-quicktime"); }
	if(fn.search(/^.*\.viv$/)>=0) {
		return("video/vivo"); }
	if(fn.search(/^.*\.vivo$/)>=0) {
		return("video/vivo"); }
	if(fn.search(/^.*\.anim[1-9j]$/)>=0) {
		return("video/x-anim"); }
	if(fn.search(/^.*\.fli$/)>=0) {
		return("video/x-flic"); }
	if(fn.search(/^.*\.flc$/)>=0) {
		return("video/x-flic"); }
	if(fn.search(/^.*\.hwp$/)>=0) {
		return("application/x-hwp"); }
	if(fn.search(/^.*\.hwt$/)>=0) {
		return("application/x-hwt"); }
	if(fn.search(/^.*\.mng$/)>=0) {
		return("video/x-mng"); }
	if(fn.search(/^.*\.asf$/)>=0) {
		return("video/x-ms-asf"); }
	if(fn.search(/^.*\.nsc$/)>=0) {
		return("application/x-netshow-channel"); }
	if(fn.search(/^.*\.wmv$/)>=0) {
		return("video/x-ms-wmv"); }
	if(fn.search(/^.*\.avi$/)>=0) {
		return("video/x-msvideo"); }
	if(fn.search(/^.*\.divx$/)>=0) {
		return("video/x-msvideo"); }
	if(fn.search(/^.*\.nsv$/)>=0) {
		return("video/x-nsv"); }
	if(fn.search(/^.*\.sdp$/)>=0) {
		return("application/sdp"); }
	if(fn.search(/^.*\.movie$/)>=0) {
		return("video/x-sgi-movie"); }
	if(fn.search(/^.*\.emp$/)>=0) {
		return("application/vnd.emusic-emusic_package"); }
	if(fn.search(/^.*\.ica$/)>=0) {
		return("application/x-ica"); }
	if(fn.search(/^.*\.xul$/)>=0) {
		return("application/vnd.mozilla.xul+xml"); }
	if(fn.search(/^.*\.602$/)>=0) {
		return("application/x-t602"); }
	return("binary/octet-stream");
}